my:
  props:
    foo:
      bar: POJO class property
      barlist:
        - bar1
        - bar2
      barmap:
        key1: val1
        key2: val2
    foolist:
      - bar: List<POJO> property
        barlist:
          - bar3
          - bar4
          - bar5
        barmap:
          key3: val3
      - bar: BAR2
        barlist:
          - bar6
          - bar7
    innerfoo:
      buzz: Inner POJO class property