my:
  props:
    foo:
      foo-prop1: POJO class property
      foo-list-prop:
        - bar1
        - bar2
      foo-map-prop:
        key1: val1
        key2: val2
    bar-list:
      - bar: List<POJO> property
        barlist:
          - bar3
          - bar4
          - bar5
        barmap:
          key3: val3
      - bar: BAR2
        barlist:
          - bar6
          - bar7
    dummy-map:
      key1:
        dummy-prop1: key1-dummy-prop1-value
        dummy-prop2: key1-dummy-prop2-value
    innerfoo:
      buzz: Inner POJO class property
    non-static-inner-foo:
      buzz: Non-static inner POJO property
    inner-bar-list:
      - bar-prop: bar-prop-1
      - bar-prop: bar-prop-2
    lib-pojo1:
      lib-prop1: library class property1 value
    buzz:
      buzz-prop: buzz-prop-value
      boo:
        boo-prop: buzz-boo-prop-value
